client_config_backend: settings
client_config:
  client_id: 1022069937612-t88a9v0kl0suqd0m8kioqiqllrjtsinb.apps.googleusercontent.com
  client_secret: U5jT4JYEklbYm2FxSxCsIiNb

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file

